//! Touch API

use crate::Coord;

/// A unique Id for a touch, used for tracking fingers
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct Id(#[doc(hidden)] usize);

/// Event generated by touch
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct Event {
    pub pos: Coord,
    pub phase: Phase,
}

/// Event generated by touch
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Phase {
    /// The start of a touch event
    Start,
    /// Touch finished
    End,
    /// Finger was moved
    Move,
    /// Touch event was cancelled
    Cancel,
}