stages:
  - build
  - deploy

everything:
  stage: build
  image: rustlang/rust:nightly
  script:
    - rustup target add wasm32-wasi
    - cargo test --all --verbose

signaling:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --package vg-signaling --release --verbose --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -ravO target/x86_64-unknown-linux-gnu/release/vg-signaling root@frontend.noxim.xyz:/opt/vg-signaling/
  only:
    - main

format:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt
  allow_failure: true