[package]
name = "vg-network"
version = "0.1.0"
edition = "2021"


[dependencies]
vg-interface = { workspace = true }

anyhow = "1"
instant = "0.1"
matchbox_socket = { workspace = true }
futures = "0.3"
uuid = "1"

serde = { version = "1", features = ["derive"] }
bincode = "1"

tracing = "0.1"
