build:
	PATH=$$PATH:/opt/devkitpro/devkitA64/bin ./build-debug.sh
run:
	PATH=$$PATH:/opt/devkitpro/devkitA64/bin ./build-debug.sh
	Ryujinx build.nro
clean:
	rm -rf target build.nro
release:
	PATH=$$PATH:/opt/devkitpro/devkitA64/bin ./build-release.sh
