use vg_types::Key;
use winit::event::VirtualKeyCode;

pub fn winit_to_key(key: VirtualKeyCode) -> Option<Key> {
    match key {
        VirtualKeyCode::A => Some(vg_types::Key::A),
        VirtualKeyCode::B => Some(vg_types::Key::B),
        VirtualKeyCode::C => Some(vg_types::Key::C),
        VirtualKeyCode::D => Some(vg_types::Key::D),
        VirtualKeyCode::E => Some(vg_types::Key::E),
        VirtualKeyCode::F => Some(vg_types::Key::F),
        VirtualKeyCode::G => Some(vg_types::Key::G),
        VirtualKeyCode::H => Some(vg_types::Key::H),
        VirtualKeyCode::I => Some(vg_types::Key::I),
        VirtualKeyCode::J => Some(vg_types::Key::J),
        VirtualKeyCode::K => Some(vg_types::Key::K),
        VirtualKeyCode::L => Some(vg_types::Key::L),
        VirtualKeyCode::M => Some(vg_types::Key::M),
        VirtualKeyCode::N => Some(vg_types::Key::N),
        VirtualKeyCode::O => Some(vg_types::Key::O),
        VirtualKeyCode::P => Some(vg_types::Key::P),
        VirtualKeyCode::Q => Some(vg_types::Key::Q),
        VirtualKeyCode::R => Some(vg_types::Key::R),
        VirtualKeyCode::S => Some(vg_types::Key::S),
        VirtualKeyCode::T => Some(vg_types::Key::T),
        VirtualKeyCode::U => Some(vg_types::Key::U),
        VirtualKeyCode::V => Some(vg_types::Key::V),
        VirtualKeyCode::W => Some(vg_types::Key::W),
        VirtualKeyCode::X => Some(vg_types::Key::X),
        VirtualKeyCode::Y => Some(vg_types::Key::Y),
        VirtualKeyCode::Z => Some(vg_types::Key::Z),
        VirtualKeyCode::Left => Some(vg_types::Key::Left),
        VirtualKeyCode::Right => Some(vg_types::Key::Right),
        VirtualKeyCode::Up => Some(vg_types::Key::Up),
        VirtualKeyCode::Down => Some(vg_types::Key::Down),
        VirtualKeyCode::Space => Some(vg_types::Key::Space),
        VirtualKeyCode::LShift => Some(vg_types::Key::Shift),
        VirtualKeyCode::LControl => Some(vg_types::Key::Control),
        VirtualKeyCode::Tab => Some(vg_types::Key::Tab),
        VirtualKeyCode::Key1 => Some(vg_types::Key::Num1),
        VirtualKeyCode::Key2 => Some(vg_types::Key::Num2),
        VirtualKeyCode::Key3 => Some(vg_types::Key::Num3),
        VirtualKeyCode::Key4 => Some(vg_types::Key::Num4),
        VirtualKeyCode::Key5 => Some(vg_types::Key::Num5),
        VirtualKeyCode::Key6 => Some(vg_types::Key::Num6),
        VirtualKeyCode::Key7 => Some(vg_types::Key::Num7),
        VirtualKeyCode::Key8 => Some(vg_types::Key::Num8),
        VirtualKeyCode::Key9 => Some(vg_types::Key::Num9),
        VirtualKeyCode::Key0 => Some(vg_types::Key::Num0),
        VirtualKeyCode::Escape => Some(vg_types::Key::Escape),
        _ => None,
    }
}
